[package]
name = "randomness_collect"
version = "0.1.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[dependencies]
codec = { version = "1.3.6", package = "parity-scale-codec", default-features = false }
hex = { version = "0.4.2", default-features = false}
lite-json = { version = "0.1", default-features = false }

frame-system = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
frame-support = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-consensus-vrf = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-consensus-babe = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-std = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1",default-features = false }
sp-io = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1",default-features = false }
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1",default-features = false }
sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1",default-features = false }
sp-application-crypto = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1",default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "hex/std",
    "lite-json/std",

    "frame-support/std",
    "sp-consensus-vrf/std",
    "sp-consensus-babe/std",
    "sp-std/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-core/std",
    "sp-application-crypto/std",
]
