[package]
name = "jupiter-cli"
version = "1.0.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
parking_lot = "0.10.0"
serde_json = "1.0"
hex-literal = "0.2.1"

sc-authority-discovery = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-basic-authorship = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-network = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-babe = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-finality-grandpa = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-rpc = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-inherents = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus-babe = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-finality-grandpa = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-authority-discovery = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

sc-cli = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
sc-service = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }

pallet-authority-discovery = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-im-online = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-staking = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# vendor
# pallet-contracts = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-contracts = { path = "../../../vendor/substrate/frame/contracts" }

jupiter-primitives = { path = "../../../primitives" }
jupiter-runtime = { path = "../../../runtime/jupiter" }
jupiter-runtime-common = { path = "../../../runtime/common" }
jupiter-executor = { path = "../executor" }
jupiter-rpc = { path = "../../../rpc" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

[features]
default = ["cli"]
cli = [
    "sc-cli",
    "sc-service",
    "jupiter-executor/wasmi-errno",
]
wasmtime = [
    "sc-cli/wasmtime",
    "sc-service/wasmtime",
    "jupiter-executor/wasmtime",
]
