[package]
name = "jupiter-dev-cli"
version = "1.0.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
parking_lot = "0.10.0"
serde_json = "1.0"

sc-cli = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1", features = ["wasmtime"] }
sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-executor = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-service = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-inherents = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-manual-seal = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-timestamp = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-basic-authorship = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

pallet-contracts = { package = "pallet-contracts", path = "../../../vendor/substrate/frame/contracts" }

frame-benchmarking = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-benchmarking-cli = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

jupiter-primitives = { path = "../../../primitives" }
jupiter-dev-runtime = { path = "../../../runtime/jupiter-dev" }
# jupiter-dev-executor = { path = "../executor" }
jupiter-rpc = { path = "../../../rpc" }
jupiter-io = { path = "../../../primitives/io" }


[build-dependencies]
substrate-build-script-utils = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }


[features]
runtime-benchmarks = [
	"jupiter-dev-runtime/runtime-benchmarks",
]
